<a href="https://colab.research.google.com/github/Oussema789/Speech_to_Text-app/blob/master/Handwritten_digits_Classification(Using_KNN_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
# import the necessary packages
#The reason is that the cross_validation module has been deprecated in recent versions of scikit-learn (since version 0.20)
#and replaced with model_selection.


from __future__ import print_function
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import datasets
from skimage import exposure
import numpy as np
import cv2
import matplotlib.pyplot as plt


In [21]:
# load the MNIST digits dataset

mnist = datasets.load_digits()
print(mnist.images)

[[[ 0.  0.  5. ...  1.  0.  0.]
  [ 0.  0. 13. ... 15.  5.  0.]
  [ 0.  3. 15. ... 11.  8.  0.]
  ...
  [ 0.  4. 11. ... 12.  7.  0.]
  [ 0.  2. 14. ... 12.  0.  0.]
  [ 0.  0.  6. ...  0.  0.  0.]]

 [[ 0.  0.  0. ...  5.  0.  0.]
  [ 0.  0.  0. ...  9.  0.  0.]
  [ 0.  0.  3. ...  6.  0.  0.]
  ...
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  0. ... 10.  0.  0.]]

 [[ 0.  0.  0. ... 12.  0.  0.]
  [ 0.  0.  3. ... 14.  0.  0.]
  [ 0.  0.  8. ... 16.  0.  0.]
  ...
  [ 0.  9. 16. ...  0.  0.  0.]
  [ 0.  3. 13. ... 11.  5.  0.]
  [ 0.  0.  0. ... 16.  9.  0.]]

 ...

 [[ 0.  0.  1. ...  1.  0.  0.]
  [ 0.  0. 13. ...  2.  1.  0.]
  [ 0.  0. 16. ... 16.  5.  0.]
  ...
  [ 0.  0. 16. ... 15.  0.  0.]
  [ 0.  0. 15. ... 16.  0.  0.]
  [ 0.  0.  2. ...  6.  0.  0.]]

 [[ 0.  0.  2. ...  0.  0.  0.]
  [ 0.  0. 14. ... 15.  1.  0.]
  [ 0.  4. 16. ... 16.  7.  0.]
  ...
  [ 0.  0.  0. ... 16.  2.  0.]
  [ 0.  0.  4. ... 16.  2.  0.]
  [ 0.  0.  5. ... 12.  0.  

In the code snippet you provided, the function datasets.load_digits() is used to load the MNIST digits dataset. Let's break it down:

In the code snippet you provided, the function `datasets.load_digits()` is used to load the MNIST digits dataset. Let's break it down:

1. **MNIST Dataset**: The MNIST dataset is a popular benchmark dataset in the field of machine learning. It consists of a collection of handwritten digits (0-9) that are commonly used for training and evaluating classification algorithms. Each image in the dataset is a grayscale image of size 28x28 pixels.

2. **`datasets` module**: The `datasets` module is part of the scikit-learn library (`sklearn`). It provides various datasets for practicing and testing machine learning algorithms.

3. **`load_digits()` function**: `load_digits()` is a function provided by the `datasets` module. When called, it loads the MNIST digits dataset and returns it as a dictionary-like object.

4. **Returned object**: The `load_digits()` function returns an object with the following attributes:
   - `data`: A 2D array representing the pixel values of each image in the dataset. Each row of the array corresponds to a flattened 8x8 image (64 pixels).
   - `target`: An array of the corresponding labels or target values for each image. Each value in the array represents the digit (0-9) associated with the corresponding image.
   - `images`: A 3D array of shape (n_samples, 8, 8) containing the original images in their original 8x8 shape.
   - `DESCR`: A description of the dataset.

In your code snippet, the `mnist` variable is assigned the dictionary-like object returned by `datasets.load_digits()`. By accessing the attributes of this object, you can access the input data (`mnist.data`), target values (`mnist.target`), original images (`mnist.images`), and dataset description (`mnist.DESCR`).

Overall, by using `datasets.load_digits()`, you can easily load the MNIST digits dataset into your code and access its associated data and labels for further processing or training machine learning models.

[15]


In [22]:
# take the MNIST data and construct the training and testing split, using 75% of the
# data for training and 25% for testing

(trainData, testData, trainLabels, testLabels) = train_test_split(np.array(mnist.data),
mnist.target, test_size=0.25, random_state=42)

In the provided code snippet, the `train_test_split` function is used to split the MNIST dataset into training and testing sets. Let's understand the function and its parameters:

1. **`train_test_split` function**: `train_test_split` is a function from the `model_selection` module of scikit-learn (`sklearn`). It allows for randomly splitting a dataset into two or more subsets for training and testing machine learning models.

2. **Input Parameters**:
   - `np.array(mnist.data)`: The input dataset, which is the pixel values of the MNIST digits. It is converted to a NumPy array using `np.array()` to ensure compatibility with the `train_test_split` function.
   - `mnist.target`: The target values or labels corresponding to each image in the MNIST dataset.
   - `test_size=0.25`: The proportion of the dataset to be allocated for testing. Here, 25% of the data will be used for testing, and the remaining 75% will be used for training.
   - `random_state=42`: The random state or seed used for randomizing the data splits. Setting a specific random state ensures reproducibility, meaning that the same splits will be obtained each time the code is run.

3. **Returned Values**:
   The `train_test_split` function returns four arrays:
   - `trainData`: The training data, which contains a subset of the MNIST data for training the machine learning model.
   - `testData`: The testing data, which contains a subset of the MNIST data for evaluating the performance of the trained model.
   - `trainLabels`: The labels or target values corresponding to the training data.
   - `testLabels`: The labels or target values corresponding to the testing data.

By using `train_test_split` with the specified parameters, the MNIST dataset is divided into training and testing sets. The training set (`trainData` and `trainLabels`) will consist of 75% of the original data, while the testing set (`testData` and `testLabels`) will contain 25% of the data. These splits allow for training a machine learning model on a subset of the data and then evaluating its performance on unseen data.

In [23]:
# now, let's take 10% of the training data and use that for validation

(trainData, valData, trainLabels, valLabels) = train_test_split(trainData, trainLabels,
test_size=0.1, random_state=84)


In [24]:
# show the sizes of each data split

print("training data points: {}".format(len(trainLabels)))
print("validation data points: {}".format(len(valLabels)))
print("testing data points: {}".format(len(testLabels)))


training data points: 1212
validation data points: 135
testing data points: 450


In [25]:
# initialize the values of k for our k-Nearest Neighbor classifier along with the
# list of accuracies for each value of k

kVals = range(1, 30, 2)
accuracies = []


In [26]:
# loop over various values of `k` for the k-Nearest Neighbor classifier

for k in range(1, 30, 2):
          # train the k-Nearest Neighbor classifier with the current value of `k`
          model = KNeighborsClassifier(n_neighbors=k)
          model.fit(trainData, trainLabels)
          # evaluate the model and update the accuracies list
          score = model.score(valData, valLabels)
          print("k=%d, accuracy=%.2f%%" % (k, score * 100))
          accuracies.append(score)

k=1, accuracy=99.26%
k=3, accuracy=99.26%
k=5, accuracy=99.26%
k=7, accuracy=99.26%
k=9, accuracy=99.26%
k=11, accuracy=99.26%
k=13, accuracy=99.26%
k=15, accuracy=99.26%
k=17, accuracy=98.52%
k=19, accuracy=98.52%
k=21, accuracy=97.78%
k=23, accuracy=97.04%
k=25, accuracy=97.78%
k=27, accuracy=97.04%
k=29, accuracy=97.04%


In the provided code snippet, a loop is used to iterate over various values of `k` for the k-Nearest Neighbor classifier. Here's a breakdown of the code:

1. **`for` loop**: The loop iterates over the range of values from 1 to 30 (exclusive) with a step size of 2. This means that it will iterate over odd values of `k` starting from 1 and up to 29.

2. **Training the k-Nearest Neighbor classifier**:
   - `model = KNeighborsClassifier(n_neighbors=k)`: A new instance of the KNeighborsClassifier class is created, specifying the number of neighbors (`n_neighbors`) as the current value of `k`. This defines the k-Nearest Neighbor classifier model with the current number of neighbors.
   - `model.fit(trainData, trainLabels)`: The created model is trained using the training data (`trainData`) and their corresponding labels (`trainLabels`).

3. **Evaluating the model and updating accuracies**:
   - `score = model.score(valData, valLabels)`: The trained model is evaluated using the validation data (`valData`) and their corresponding labels (`valLabels`). The `score` represents the accuracy of the model on the validation set.
   - `print("k=%d, accuracy=%.2f%%" % (k, score * 100))`: The current value of `k` and its corresponding accuracy are printed to the console. The accuracy is formatted as a percentage using string formatting.
   - `accuracies.append(score)`: The accuracy value is appended to the `accuracies` list, which can be used later for further analysis or visualization.

The purpose of this code is to train and evaluate the k-Nearest Neighbor classifier with different values of `k`. By iterating over various values of `k` and evaluating the model's accuracy, the code helps in determining the optimal number of neighbors for the KNN algorithm on the given dataset.

Typically, the loop starts with a small value of `k` (such as 1) and gradually increases it to larger odd values. This allows for observing how the accuracy of the model changes with different numbers of neighbors and helps in selecting the best `k` value for the KNN classifier.

In [27]:
# find the value of k that has the largest accuracy

i = np.argmax(accuracies)
print("k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[i],
accuracies[i] * 100))

k=1 achieved highest accuracy of 99.26% on validation data


In the provided code snippet, the value of `k` that achieved the highest accuracy on the validation data is determined. Here's how it works:

1. **`np.argmax()` function**: The `argmax()` function from the NumPy library is used to find the index of the maximum value in the `accuracies` list. It returns the index of the first occurrence of the maximum value.

2. **Finding the index and value of `k` with the highest accuracy**:
   - `i = np.argmax(accuracies)`: The `argmax()` function is applied to the `accuracies` list, and the resulting index of the maximum accuracy is stored in the variable `i`.
   - `kVals[i]`: The corresponding `k` value for the maximum accuracy is obtained from the `kVals` list using the index `i`.
   - `accuracies[i] * 100`: The highest accuracy value is obtained by accessing the element in the `accuracies` list at index `i` and multiplying it by 100 to represent it as a percentage.

3. **Printing the results**:
   - `print("k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[i], accuracies[i] * 100))`: The value of `k` that achieved the highest accuracy is printed along with the corresponding accuracy value. The `%d` and `%.2f` are placeholders for the integer (`kVals[i]`) and float (`accuracies[i] * 100`) values, respectively.

By using `np.argmax()` to find the index of the maximum accuracy and then accessing the corresponding `k` value and accuracy from the lists, the code determines which value of `k` achieved the highest accuracy on the validation data. This information is then printed to the console.

In [29]:
# re-train our classifier using the best k value and predict the labels of the
# test data

model = KNeighborsClassifier(n_neighbors=kVals[i])
model.fit(trainData, trainLabels)
predictions = model.predict(testData)
print(predictions[1])


9


In the provided code snippet, the k-Nearest Neighbor classifier is retrained using the best value of `k` that achieved the highest accuracy on the validation data. The classifier is then used to predict the labels of the test data. Here's how it works:

1. **Retraining the classifier with the best `k` value**:
   - `model = KNeighborsClassifier(n_neighbors=kVals[i])`: A new instance of the KNeighborsClassifier class is created, specifying the number of neighbors (`n_neighbors`) as the best `k` value obtained from `kVals[i]`.
   - `model.fit(trainData, trainLabels)`: The classifier is retrained using the training data (`trainData`) and their corresponding labels (`trainLabels`) with the best `k` value.

2. **Predicting the labels of the test data**:
   - `predictions = model.predict(testData)`: The trained classifier is used to predict the labels of the test data (`testData`).

3. **Printing a sample prediction**:
   - `print(predictions[1])`: The predicted label of the second sample in the test data is printed to the console. The index `1` is used to access the second element in the `predictions` array.

By retraining the classifier with the best `k` value and using it to predict the labels of the test data, the code allows you to evaluate the performance of the classifier on unseen data. Printing a sample prediction provides a glimpse of the predicted label for a specific test sample, in this case, the second sample in the test data.

In [30]:
# show a final classification report demonstrating the accuracy of the classifier
# for each of the digits

print("EVALUATION ON TESTING DATA")
print(classification_report(testLabels, predictions))

print ("Confusion matrix")
print(confusion_matrix(testLabels,predictions))

EVALUATION ON TESTING DATA
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       0.95      1.00      0.97        37
           2       1.00      1.00      1.00        38
           3       0.98      0.98      0.98        46
           4       0.98      0.98      0.98        55
           5       0.98      1.00      0.99        59
           6       1.00      1.00      1.00        45
           7       1.00      0.98      0.99        41
           8       0.97      0.95      0.96        38
           9       0.96      0.94      0.95        48

    accuracy                           0.98       450
   macro avg       0.98      0.98      0.98       450
weighted avg       0.98      0.98      0.98       450

Confusion matrix
[[43  0  0  0  0  0  0  0  0  0]
 [ 0 37  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 45  0  0  0  0  1  0]
 [ 0  1  0  0 54  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]

In the provided code snippet, the final classification report and confusion matrix are displayed to evaluate the accuracy of the classifier on the testing data. Here's how it works:

1. **Printing the evaluation on testing data**:
   - `print("EVALUATION ON TESTING DATA")`: A header is printed to indicate the following information is related to the evaluation on the testing data.
   - `print(classification_report(testLabels, predictions))`: The `classification_report()` function from the `metrics` module is used to generate a report that includes various performance metrics such as precision, recall, F1-score, and support for each class. It takes the true labels (`testLabels`) and the predicted labels (`predictions`) as input, and the resulting report is printed to the console. This report provides a summary of the classifier's performance for each digit class.

2. **Printing the confusion matrix**:
   - `print("Confusion matrix")`: A header is printed to indicate that the following information is the confusion matrix.
   - `print(confusion_matrix(testLabels, predictions))`: The `confusion_matrix()` function from the `metrics` module is used to compute the confusion matrix based on the true labels (`testLabels`) and the predicted labels (`predictions`). The resulting confusion matrix is printed to the console. The confusion matrix provides information about the number of samples that were correctly or incorrectly classified for each class.

By printing the classification report and confusion matrix, the code allows you to gain insights into the overall accuracy and performance of the classifier on the testing data. The classification report provides a detailed analysis of the classifier's performance for each digit class, while the confusion matrix gives a more granular view of the classification results for each class.

In [ ]:
# loop over a few random digits

for i in np.random.randint(0, high=len(testLabels), size=(5,)):
         # grab the image and classify it
         image = testData[i]
         prediction = model.predict([image])[0]
         # convert the image for a 64-dim array to an 8 x 8 image compatible with OpenCV,
         # then resize it to 32 x 32 pixels so we can see it better
##         image = image.reshape((64, 64))
##         image = exposure.rescale_intensity(image, out_range=(0, 255))
##         image = imutils.resize(image, width=32, inter=cv2.INTER_CUBIC)

         # show the prediction

         imgdata = np.array(image, dtype='float')
         pixels = imgdata.reshape((8,8))
         plt.imshow(pixels,cmap='gray')
         plt.annotate(prediction,(3,3),bbox={'facecolor':'white'},fontsize=16)
         print("i think tha digit is : {}".format(prediction))
         #cv2.imshow("image", image)
         plt.show()
         cv2.waitKey(0)

In the provided code snippet, a loop is used to randomly select a few digits from the test data and classify them using the trained model. Here's how it works:

1. **Looping over random digits**:
   - `for i in np.random.randint(0, high=len(testLabels), size=(5,)):`: The loop iterates over a randomly generated array of indices. `np.random.randint()` function is used to generate 5 random integers within the range of indices of the test data (`0` to `len(testLabels)`). These indices are stored in the variable `i` during each iteration.

2. **Classifying and displaying the digit images**:
   - `image = testData[i]`: The image data corresponding to the randomly selected index `i` is retrieved from the `testData` array and stored in the variable `image`.
   - `prediction = model.predict([image])[0]`: The trained model is used to predict the label of the current `image`. The predicted label is stored in the variable `prediction`.
   - `imgdata = np.array(image, dtype='float')`: The `image` is converted to a NumPy array of type float.
   - `pixels = imgdata.reshape((8,8))`: The 1D array of pixels is reshaped to a 2D array representing an 8x8 image.
   - `plt.imshow(pixels,cmap='gray')`: The image is displayed using the `imshow()` function from matplotlib with the grayscale color map (`'gray'`).
   - `plt.annotate(prediction,(3,3),bbox={'facecolor':'white'},fontsize=16)`: The predicted label is annotated on the image plot at coordinates (3, 3) with a white background color and font size 16.
   - `print("i think the digit is: {}".format(prediction))`: The predicted label is printed to the console.
   - `plt.show()`: The image plot with the annotation is displayed.
   - `cv2.waitKey(0)`: This line is commented out in the code snippet, but it is typically used in OpenCV to wait for a keyboard event. It allows the user to close the displayed image by pressing any key.

By looping over a few randomly selected digits from the test data, the code classifies each digit using the trained model and displays the digit image along with the predicted label. This allows you to visually inspect the performance of the classifier on individual digits and compare the predicted labels with the ground truth labels.